project_id = "hmiypsikrqgomawbcimq"

[functions.publish-tweet]
verify_jwt = false

[functions.analyze-social-sentiment]
verify_jwt = false

[functions.fetch-market-news]
verify_jwt = false

[functions.fetch-social-posts]
verify_jwt = false

[functions.validate-predictions]
verify_jwt = false

[functions.simulate-trading]
verify_jwt = false

[functions.improve-algorithm]
verify_jwt = false

[functions.fetch-seeking-alpha]
verify_jwt = false

[functions.analyze-news-nlp]
verify_jwt = false
